export const flujosChatbot = [
  {
    id: 'taxi',
    icono: '➤',
    titulo: 'Cotizar Taxi Aéreo',
    imagen: '/imagenes/taxi-aereo.png',
    alt: 'Servicio ejecutivo de taxi aéreo',
    descripcion: 'Cotización de vuelos privados nacionales e internacionales bajo demanda.',
    preguntas: [
      { clave: 'origen', etiqueta: 'Origen', texto: '¿Cuál es el origen del vuelo?' },
      { clave: 'destino', etiqueta: 'Destino', texto: '¿Cuál es el destino?' },
      { clave: 'fecha', etiqueta: 'Fecha', texto: '¿Qué fecha desea volar?' },
      { clave: 'hora', etiqueta: 'Hora', texto: '¿A qué hora aproximadamente?' },
      { clave: 'pasajeros', etiqueta: 'Pasajeros', texto: '¿Cuántos pasajeros viajarán?' },
      { clave: 'tipoViaje', etiqueta: 'Tipo de viaje', texto: '¿Será viaje sencillo o redondo?' },
      { clave: 'equipaje', etiqueta: 'Equipaje', texto: '¿Llevarán equipaje especial?' },
      { clave: 'nombre', etiqueta: 'Nombre', texto: '¿Cuál es su nombre completo?' },
      { clave: 'telefono', etiqueta: 'Teléfono', texto: '¿Cuál es su teléfono o WhatsApp?' },
    ],
  },
  {
    id: 'compra',
    icono: '✈',
    titulo: 'Comprar Aeronave',
    imagen: '/imagenes/Compraventa.png',
    alt: 'Jet ejecutivo representado para venta',
    descripcion: 'Asesoría especializada para localizar y adquirir aeronaves ejecutivas.',
    preguntas: [
      { clave: 'tipoAeronave', etiqueta: 'Tipo de aeronave', texto: '¿Qué tipo de aeronave busca?' },
      { clave: 'presupuesto', etiqueta: 'Presupuesto', texto: '¿Cuál es su presupuesto aproximado?' },
      { clave: 'anio', etiqueta: 'Año', texto: '¿Tiene un año o rango de años deseado?' },
      { clave: 'uso', etiqueta: 'Uso', texto: '¿El uso será personal, corporativo o comercial?' },
      { clave: 'ubicacion', etiqueta: 'Ubicación', texto: '¿En qué país o ciudad desea operar?' },
      { clave: 'nombre', etiqueta: 'Nombre', texto: '¿Cuál es su nombre completo?' },
      { clave: 'telefono', etiqueta: 'Teléfono', texto: '¿Cuál es su teléfono o WhatsApp?' },
    ],
  },
  {
    id: 'venta',
    icono: '⇄',
    titulo: 'Vender Aeronave',
    imagen: '/imagenes/Ventas.png',
    alt: 'Representación comercial para vender una aeronave',
    descripcion: 'Representación y acompañamiento comercial para vender aeronaves ejecutivas.',
    preguntas: [
      { clave: 'modelo', etiqueta: 'Modelo', texto: '¿Qué modelo de aeronave desea vender?' },
      { clave: 'anio', etiqueta: 'Año', texto: '¿De qué año es la aeronave?' },
      { clave: 'matricula', etiqueta: 'Matrícula', texto: '¿Cuál es la matrícula?' },
      { clave: 'horas', etiqueta: 'Horas de vuelo', texto: '¿Cuántas horas de vuelo tiene aproximadamente?' },
      { clave: 'ubicacion', etiqueta: 'Ubicación', texto: '¿Dónde se encuentra actualmente?' },
      { clave: 'documentacion', etiqueta: 'Documentación', texto: '¿Cuenta con documentación actualizada?' },
      { clave: 'nombre', etiqueta: 'Nombre', texto: '¿Cuál es su nombre completo?' },
      { clave: 'telefono', etiqueta: 'Teléfono', texto: '¿Cuál es su teléfono o WhatsApp?' },
    ],
  },
  {
    id: 'administracion',
    icono: '▤',
    titulo: 'Administración de Aeronaves',
    imagen: '/imagenes/Administracion.png',
    alt: 'Administración integral de aeronaves',
    descripcion: 'Gestión de operación, mantenimiento, tripulación y documentación.',
    preguntas: [
      { clave: 'modelo', etiqueta: 'Modelo', texto: '¿Qué modelo de aeronave tiene?' },
      { clave: 'matricula', etiqueta: 'Matrícula', texto: '¿Cuál es la matrícula?' },
      { clave: 'ubicacion', etiqueta: 'Ubicación', texto: '¿Dónde opera principalmente?' },
      { clave: 'necesidad', etiqueta: 'Necesidad', texto: '¿Qué necesita administrar: operación, mantenimiento, tripulación o documentación?' },
      { clave: 'nombre', etiqueta: 'Nombre', texto: '¿Cuál es su nombre completo?' },
      { clave: 'telefono', etiqueta: 'Teléfono', texto: '¿Cuál es su teléfono o WhatsApp?' },
    ],
  },
  {
    id: 'precompra',
    icono: '⌕',
    titulo: 'Inspección Precompra',
    imagen: '/imagenes/inspeccionprecompra.png',
    alt: 'Técnico realizando una inspección precompra',
    descripcion: 'Revisión técnica y documental antes de adquirir una aeronave.',
    preguntas: [
      { clave: 'modelo', etiqueta: 'Modelo', texto: '¿Qué modelo de aeronave desea inspeccionar?' },
      { clave: 'anio', etiqueta: 'Año', texto: '¿De qué año es?' },
      { clave: 'ubicacion', etiqueta: 'Ubicación', texto: '¿Dónde se encuentra la aeronave?' },
      { clave: 'fechaCompra', etiqueta: 'Fecha de compra', texto: '¿Cuándo planea realizar la compra?' },
      { clave: 'documentos', etiqueta: 'Documentos', texto: '¿Ya cuenta con documentación disponible?' },
      { clave: 'nombre', etiqueta: 'Nombre', texto: '¿Cuál es su nombre completo?' },
      { clave: 'telefono', etiqueta: 'Teléfono', texto: '¿Cuál es su teléfono o WhatsApp?' },
    ],
  },
  {
    id: 'motores',
    icono: '⚙',
    titulo: 'Taller de Motores',
    imagen: '/imagenes/tallermotores.png',
    alt: 'Técnico trabajando en un motor aeronáutico',
    descripcion: 'Inspección, diagnóstico, mantenimiento y reparación de motores.',
    preguntas: [
      { clave: 'tipoAeronave', etiqueta: 'Aeronave', texto: '¿Qué tipo de aeronave es?' },
      { clave: 'motor', etiqueta: 'Motor', texto: '¿Qué modelo de motor tiene?' },
      { clave: 'servicio', etiqueta: 'Servicio', texto: '¿Necesita inspección, diagnóstico, mantenimiento o reparación?' },
      { clave: 'urgencia', etiqueta: 'Urgencia', texto: '¿Qué nivel de urgencia tiene?' },
      { clave: 'ubicacion', etiqueta: 'Ubicación', texto: '¿Dónde se encuentra la aeronave?' },
      { clave: 'nombre', etiqueta: 'Nombre', texto: '¿Cuál es su nombre completo?' },
      { clave: 'telefono', etiqueta: 'Teléfono', texto: '¿Cuál es su teléfono o WhatsApp?' },
    ],
  },
]
